<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

 <!-- constants -->
    <xacro:property name="camera_length" value = "0.02" />
    <xacro:property name="camera_width" value = "0.025" />
    <xacro:property name="camera_height" value = "0.025" />
    <xacro:property name="camera_mass" value = "0.1" />
    <xacro:property name="camera_mount_length" value = "0.01" />
    <xacro:property name="camera_mount_width" value = "0.080" />
    <xacro:property name="camera_mount_heigth" value = "0.115" />
    <xacro:property name="camera_mount_mass" value = "0.1" />
    <xacro:property name="camera_offset_x" value = "${camera_length/2 + camera_mount_length/2}" />
    <xacro:property name="camera_offset_z" value = "${camera_mount_heigth/2 - camera_height/2}" />
    <xacro:property name="camera_mount_offset_x" value = "-0.035" />
    <xacro:property name="camera_mount_offset_z" value = "${camera_mount_heigth/2 + chassis_height/2}" />

    <!-- camera_mount_joint -->
    <joint name="camera_mount_joint" type="fixed">
        <parent link="chassis_link" />
        <child link="camera_mount_link" />
        <origin xyz="${camera_mount_offset_x} 0 ${camera_mount_offset_z}" rpy="0 0 0" />
    </joint>

    <!-- camera_mount_link -->
    <link name="camera_mount_link">
        <visual>
            <geometry>
                <box size="${camera_mount_length} ${camera_mount_width} ${camera_mount_heigth}" />
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <box size="${camera_mount_length} ${camera_mount_width} ${camera_mount_heigth}" />
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        </collision>
        <xacro:box_inertia m="${camera_mass}" l="${camera_mount_length}" w="${camera_mount_width}" h="${camera_mount_heigth}"
                        xyz="0 0 0" rpy="0 0 0" />
    </link>

    <!-- camera_joint -->
    <joint name="camera_joint" type="fixed">
        <parent link="camera_mount_link" />
        <child link="camera_link" />
        <origin xyz="${camera_offset_x} 0 ${camera_offset_z}" rpy="0 0 0" />
    </joint>

    <!-- camera_link -->
    <link name="camera_link">
        <visual>
            <geometry>
                <box size="${camera_length} ${camera_width} ${camera_height}" />
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <material name="red"/>
        </visual>
        <collision>
            <geometry>
                <box size="${camera_length} ${camera_width} ${camera_height}" />
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        </collision>
        <xacro:box_inertia m="${camera_mass}" l="${camera_length}" w="${camera_width}" h="${camera_height}"
                        xyz="0 0 0" rpy="0 0 0" />
    </link>

    <!-- Gazebo parameters for camera sensor -->
    <gazebo reference="camera_link">
        <material>Gazebo/Red</material>

        <sensor name="camera" type="camera">
            <pose> 0 0 0 0 0 0 </pose>
            <visualize>true</visualize>
            <update_rate>10</update_rate>
            <camera>
                <horizontal_fov>1.089</horizontal_fov>
                <image>
                    <format>R8G8B8</format>
                    <width>640</width>
                    <height>480</height>
                </image>
                <clip>
                    <near>0.05</near>
                    <far>8.0</far>
                </clip>
            </camera>
            <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
                <frame_name>camera_link_optical</frame_name>
            </plugin>
        </sensor>
    </gazebo>

</robot>