# initializes joy_node and teleop_node 
# parameters for joy_node
joy_node:
  ros__parameters:
        device_id: 0
        deadzone: 0.05
        autorepeat_rate: 20.0

# parameters for teleop_node
teleop_node:
  ros__parameters:
        axis_linear.x: 1 # forward/reverse axis
        scale_linear.x: 0.5
        scale_linear_turbo.x: 1.0
        axis_angular.yaw: 4 # right/left axis
        scale_angular.yaw: 0.75
        scale_angular_turbo.yaw: 1.0
        require_enable_button: true
        enable_button: 4  # deadman button
        enable_turbo_button: 5  # turbo button
