<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">


        <!-- colors -->

        <gazebo reference="chassis_link">

                <material>Gazebo/Blue</material>

        </gazebo>


        <gazebo reference="right_wheel_link">

                <material>Gazebo/Orange</material>

        </gazebo>


        <gazebo reference="left_wheel_link">

                <material>Gazebo/Orange</material>

        </gazebo>


        <gazebo reference="caster_wheel_link">

                <material>Gazebo/Orange</material>

                <mu1 value="0.001" />

                <mu2 value="0.001" />

        </gazebo>


        <gazebo>

                <plugin name="gazebo_ros_diff_drive" filename="libgazebo_ros_diff_drive.so">


                        <!-- Update rate in Hz -->

                        <update_rate>50</update_rate>


                        <!-- wheels -->

                        <left_joint>left_wheel_joint</left_joint>

                        <right_joint>right_wheel_joint</right_joint>


                        <!-- kinematics -->

                        <wheel_separation>${chassis_width + wheel_diam/2}</wheel_separation>

                        <wheel_diameter>${wheel_diam}</wheel_diameter>


                        <!-- limits -->

                        <max_wheel_torque>20</max_wheel_torque>

                        <max_wheel_acceleration>1.0</max_wheel_acceleration>


                        <!-- output -->

                        <publish_odom>true</publish_odom>

                        <publish_odom_tf>true</publish_odom_tf>

                        <publish_wheel_tf>true</publish_wheel_tf>


                        <odometry_topic>odom</odometry_topic>

                        <odometry_frame>odom</odometry_frame>

                        <robot_base_frame>base_link</robot_base_frame>


                  </plugin>

        </gazebo>

</robot>