<?xml version="1.0"?>

<robot name="minibot_base" xmlns:xacro="http://www.ros.org/wiki/xacro">

        <!-- colors -->
        <material name="white">
                <color rgba="1 1 1 1"/>
        </material>

        <material name="black">
                <color rgba="0 0 0 1"/>
        </material>

        <material name="orange">
                <color rgba="1 0.3 0.1 1"/>
        </material>

        <material name="blue">
                <color rgba="0.2 0.2 1 1"/>
        </material>

        <xacro:property name="chassis_length" value = "0.216" />
        <xacro:property name="chassis_width" value = "0.114" />
        <xacro:property name="chassis_height" value = "0.036" />
        <xacro:property name="wheel_diam" value = "0.065" />
        <xacro:property name="wheel_thickness" value = "0.015" />
        <xacro:property name="wheel_offset_x" value = "${(chassis_length/2) - (wheel_diam/2)}" />
        <xacro:property name="wheel_offset_y" value = "${(chassis_width/2) + (wheel_diam/2) }" />
        <xacro:property name="wheel_offset_z" value = "${wheel_diam/2}" />
        <xacro:property name="ball_caster_diam" value = "0.0254" />
        <xacro:property name="ball_caster_offset_x" value = "-${(chassis_length/2) - ball_caster_diam}" />
        <xacro:property name="ball_caster_offset_z" value = "-${((wheel_diam/2) - (ball_caster_diam/2))}" />
        <xacro:property name="chassis_mass" value = "2" />
        <xacro:property name="wheel_mass" value = "0.5" />
        <xacro:property name="ball_caster_mass" value = "0.5" />

        <xacro:include filename="inertia_macros.xacro" />
        <xacro:include filename="minibot_gazebo.xacro" />        

        <!-- base_link -->
        <link name="base_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0 0 0"/>
            </geometry>
        </visual>
        </link>

        <!-- chassis_joint -->
        <joint name="chassis_joint" type="fixed">
            <parent link="base_link"/>
            <child link="chassis_link"/>
            <origin xyz="${-wheel_offset_x} 0 ${wheel_diam/2}" rpy="0 0 0"/>
        </joint>

        <!-- chassis_link -->
        <link name="chassis_link">
        <visual>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
                        <origin xyz="0 0 0" rpy="0 0 0"/>
            <material name="blue" />
        </visual>
                <collision>
                        <geometry>
                                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
                        </geometry>
                        <origin xyz="0 0 0" rpy="0 0 0"/>
                </collision>
                <xacro:box_inertia m="${chassis_mass}" l="${chassis_length}" w="${chassis_width}" h="${chassis_height}"
                                xyz="0 0 0" rpy="0 0 0" />
        </link>

        <!-- right_wheel_joint -->
        <joint name="right_wheel_joint" type="continuous">
                <parent link="chassis_link"/>
                <child link="right_wheel_link"/>
                <origin xyz="${wheel_offset_x} ${-((chassis_width/2) + (wheel_thickness/2))} 0" rpy="${pi/2} 0 0"/>
                <axis xyz="0 0 1"/>
        </joint>

        <!-- right_wheel_link -->
        <link name="right_wheel_link">
                <visual>
                        <geometry>
                                <cylinder length="${wheel_thickness}" radius="${wheel_diam/2}" />
                        </geometry>
            <origin xyz="0 0 0"  rpy="0 0 0"/>
                        <material name="orange" />
                </visual>
                <collision>
                        <geometry>
                                <cylinder length="${wheel_thickness}" radius="${wheel_diam/2}" />
                        </geometry>
            <origin xyz="0 0 0"  rpy="0 0 0"/>
                </collision>
                <xacro:cylinder_inertia m="${wheel_mass}" h="${wheel_thickness}" r="${wheel_diam/2}"
                                        xyz="0 0 0" rpy="0 0 0" />
        </link>        

        <!-- left_wheel_joint -->
        <joint name="left_wheel_joint" type="continuous">
                <parent link="chassis_link"/>
                <child link="left_wheel_link"/>
                <origin xyz="${wheel_offset_x} ${(chassis_width/2) + (wheel_thickness/2)} 0" rpy="${-pi/2} 0 0"/>
                <axis xyz="0 0 1"/>
        </joint>

        <!-- left_wheel_link -->
        <link name="left_wheel_link">
                <visual>
                        <geometry>
                                <cylinder length="${wheel_thickness}" radius="${wheel_diam/2}" />
                        </geometry>
            <origin xyz="0 0 0"  rpy="0 0 0"/>
                        <material name="orange"/>
                </visual>
                <collision>
                        <geometry>
                                <cylinder length="${wheel_thickness}" radius="${wheel_diam/2}" />
                        </geometry>
            <origin xyz="0 0 0"  rpy="0 0 0"/>
                </collision>
                <xacro:cylinder_inertia m="${wheel_mass}" h="${wheel_thickness}" r="${wheel_diam/2}"
                                        xyz="0 0 0" rpy="0 0 0" />
        </link>

        <!-- caster_wheel_joint -->
        <joint name="caster_wheel_joint" type="fixed">
                <parent link="chassis_link"/>
                <child link="caster_wheel_link"/>
                <origin xyz="${ball_caster_offset_x} 0 ${ball_caster_offset_z}" rpy="0 0 0"/>
        </joint>

        <!-- caster_wheel_link -->
        <link name="caster_wheel_link">
                <visual>
                        <geometry>
                                <sphere radius="${ball_caster_diam/2}" />
                        </geometry>
                        <origin xyz="0 0 0"  rpy="0 0 0"/>
                        <material name="orange"/>
                </visual>
                <collision>
                        <geometry>
                                <sphere radius="${ball_caster_diam/2}" />
                        </geometry>
                        <origin xyz="0 0 0"  rpy="0 0 0"/>
                </collision>
                <xacro:sphere_inertia m="${ball_caster_mass}" r="${ball_caster_diam/2}" xyz="0 0 0" rpy="0 0 0" />
        </link>

</robot>